module.exports = class Urls {
  constructor() {
  var api_key = 'kvaq7prj7saqwsvpll64r866k0igxuntnjlnbkhu'
  this.SITE_0 = 'https://api.rss2json.com/v1/api.json?rss_url=http%3A%2F%2Fzurineta.net%2Ffeed'
  this.SITE_1 = 'https://api.rss2json.com/v1/api.json?rss_url=http%3A%2F%2Ffc2-adult.com%2F%3Fxml'
  this.SITE_2 = 'https://api.rss2json.com/v1/api.json?rss_url=http%3A%2F%2Fsenzuritv.net%2Ffeed'
  this.SITE_3 = `https://api.rss2json.com/v1/api.json?rss_url=http%3A%2F%2Ffeticomx.com%2F%3Fxml&api_key=${api_key}`
  this.SITE_4 = `https://api.rss2json.com/v1/api.json?rss_url=http%3A%2F%2Feropuni.com%2Ffeed%2F&api_key=${api_key}`
  this.SITE_5 = `https://api.rss2json.com/v1/api.json?rss_url=http%3A%2F%2Fchijyosourou.com%2Ffeed&api_key=${api_key}`
  this.SITE_6 = `https://api.rss2json.com/v1/api.json?rss_url=http%3A%2F%2Fmaniacture.com%2Ffeed&api_key=${api_key}`
  this.SITE_7 = `https://api.rss2json.com/v1/api.json?rss_url=http%3A%2F%2Fhimitsunoseiheki.blog.fc2.com%2F%3Fxml&api_key=${api_key}`
  this.SITE_8 = `https://api.rss2json.com/v1/api.json?rss_url=http%3A%2F%2Feromon.net%2Ffeed&api_key=${api_key}`
  this.SITE_9 = `https://api.rss2json.com/v1/api.json?rss_url=http%3A%2F%2Fomecos.pink%2F%3Ffeed%3Drss2&api_key=${api_key}`
  this.SITE_10 = `https://api.rss2json.com/v1/api.json?rss_url=http%3A%2F%2Fchobitch.com%2Ffeed&api_key=${api_key}`
  this.SITE_11 = `https://api.rss2json.com/v1/api.json?rss_url=http%3A%2F%2Fmekakushiya.net%2Ffeed&api_key=${api_key}`
  this.SITE_12 = `https://api.rss2json.com/v1/api.json?rss_url=http%3A%2F%2Fadulthub.site%2Ffeed&api_key=${api_key}`
  this.SITE_13 = `https://api.rss2json.com/v1/api.json?rss_url=http%3A%2F%2Fadult-life.jp%2Ffeed&api_key=${api_key}`
  this.SITE_14 = `https://api.rss2json.com/v1/api.json?rss_url=http%3A%2F%2Ftokyoporno.blog.fc2.com%2F%3Fxml&api_key=${api_key}`
  this.SITE_15 = `https://api.rss2json.com/v1/api.json?rss_url=http%3A%2F%2Fmouth-is-the-sun.info%2Ffeed&api_key=${api_key}`
  this.SITE_16 = `https://api.rss2json.com/v1/api.json?rss_url=http%3A%2F%2Fjapanesefetish.blog.fc2.com%2F%3Fxml&api_key=${api_key}`
  this.SITE_17 = `https://api.rss2json.com/v1/api.json?rss_url=http%3A%2F%2Fbustybigboobs.xxxblog.jp%2Findex.rdf&api_key=${api_key}`
  this.SITE_18 = `https://api.rss2json.com/v1/api.json?rss_url=http%3A%2F%2Fxhamstar.blog.fc2.com%2F%3Fxml&api_key=${api_key}`
  this.SITE_19 = `https://api.rss2json.com/v1/api.json?rss_url=http%3A%2F%2Ffermusu.com%2Ffeed&api_key=${api_key}`
  this.SITE_20 = `https://api.rss2json.com/v1/api.json?rss_url=http%3A%2F%2Felolicco.com%2Ffeed%2F&api_key=${api_key}`
  this.SITE_21 = `https://api.rss2json.com/v1/api.json?rss_url=http%3A%2F%2Ferolife1919.blog.fc2.com%2F%3Fxml&api_key=${api_key}`
  this.SITE_22 = `https://api.rss2json.com/v1/api.json?rss_url=http%3A%2F%2Fchijyosourou.com%2Ffeed&api_key=${api_key}`
  this.SITE_23 = `https://api.rss2json.com/v1/api.json?rss_url=http%3A%2F%2Fero-delivery.com%2Ffeed&api_key=${api_key}`
  this.SITE_24 = ` https://api.rss2json.com/v1/api.json?rss_url=http%3A%2F%2Fmuramuraeros.com%2Ffeed&api_key=${api_key}`
  this.SITE_25 = `https://api.rss2json.com/v1/api.json?rss_url=http%3A%2F%2Froriyell.blog.fc2.com%2F%3Fxml&api_key=${api_key}`
  this.SITE_26 = `https://api.rss2json.com/v1/api.json?rss_url=http%3A%2F%2Ferorintyo.xyz%2Ffeed&api_key=${api_key}`
  this.SITE_27 = `https://api.rss2json.com/v1/api.json?rss_url=http%3A%2F%2Fxvideos-adult.net%2Ffeed&api_key=${api_key}`
  this.SITE_28 = `https://api.rss2json.com/v1/api.json?rss_url=http%3A%2F%2Flolispot.net%2Ffeed&api_key=${api_key}`
  this.SITE_29 = `https://api.rss2json.com/v1/api.json?rss_url=http%3A%2F%2Fufufundouga.blog.fc2.com%2F%3Fxml&api_key=${api_key}`
  this.SITE_30 = `https://api.rss2json.com/v1/api.json?rss_url=http%3A%2F%2Ferodouga-go.com%2F%3Ffeed%3Drss2&api_key=${api_key}`
  this.SITE_31 = `https://api.rss2json.com/v1/api.json?rss_url=http%3A%2F%2Fmania-juyoaru.com%2Ffeed&api_key=${api_key}`
  this.SITE_32 = `https://api.rss2json.com/v1/api.json?rss_url=http%3A%2F%2Fpaipan.in.net%2Ffeed%2F&api_key=${api_key}`
  this.SITE_33 = `https://api.rss2json.com/v1/api.json?rss_url=http%3A%2F%2Ferotter.net%2Ffeed%2F&api_key=${api_key}`
  this.SITE_34 = `https://api.rss2json.com/v1/api.json?rss_url=http%3A%2F%2Fwww.erox-navi.com%2Ffeed&api_key=${api_key}`
  this.SITE_35 = `https://api.rss2json.com/v1/api.json?rss_url=http%3A%2F%2Foshiri-mania.net%2Ffeed&api_key=${api_key}`
  this.SITE_36 = `https://api.rss2json.com/v1/api.json?rss_url=http%3A%2F%2Fcassisorange2223.blog.fc2.com%2F%3Fxml&api_key=${api_key}`
  this.SITE_37 = `https://api.rss2json.com/v1/api.json?rss_url=http%3A%2F%2Fona-db.xyz%2F%3Ffeed%3Drss2&api_key=${api_key}`
  this.SITE_38 = `https://api.rss2json.com/v1/api.json?rss_url=http%3A%2F%2Fwww.namachu.com%2Ffeed&api_key=${api_key}`
  this.SITE_39 = `https://api.rss2json.com/v1/api.json?rss_url=http%3A%2F%2Fadaruto.site%2Ffeed&api_key=${api_key}`
  this.SITE_40 = `https://api.rss2json.com/v1/api.json?rss_url=http%3A%2F%2Fsidedish-erodouga.net%2Ffeed&api_key=${api_key}`
  this.SITE_41 = `https://api.rss2json.com/v1/api.json?rss_url=http%3A%2F%2Ferozm.jp%2F%3Fxml&api_key=${api_key}`
  this.SITE_42 = `https://api.rss2json.com/v1/api.json?rss_url=http%3A%2F%2Famateur-fc2.com%2F%3Fxml&api_key=${api_key}`
  this.SITE_43 = `https://api.rss2json.com/v1/api.json?rss_url=http%3A%2F%2Fpakosen.com%2Ffeed&api_key=${api_key}`
  this.SITE_44 = `https://api.rss2json.com/v1/api.json?rss_url=http%3A%2F%2Feroark.net%2Ffeed%2F&api_key=${api_key}`
  this.SITE_45 = `https://api.rss2json.com/v1/api.json?rss_url=http%3A%2F%2Fkanzensiroutonanpamuryo.com%2Ffeed&api_key=${api_key}`
  this.SITE_46 = `https://api.rss2json.com/v1/api.json?rss_url=http%3A%2F%2Fosushi39.com%2Ffeed&api_key=${api_key}`
  this.SITE_47 = `https://api.rss2json.com/v1/api.json?rss_url=http%3A%2F%2Feroshiri.com%2F%3Ffeed%3Drss2&api_key=${api_key}`
  this.SITE_48 = `https://api.rss2json.com/v1/api.json?rss_url=http%3A%2F%2Ffellamovies.com%2F%3Ffeed%3Drss2&api_key=${api_key}`
  this.SITE_49 = `https://api.rss2json.com/v1/api.json?rss_url=http%3A%2F%2Feroeromuryoudouga.net%2F%3Ffeed%3Drss2&api_key=${api_key}`
  this.SITE_50 = `https://api.rss2json.com/v1/api.json?rss_url=http%3A%2F%2Fkanzentosatsumuryo.com%2Ffeed&api_key=${api_key}`
  this.SITE_51 = `https://api.rss2json.com/v1/api.json?rss_url=http%3A%2F%2Foshirikizoku.com%2Ffeed&api_key=${api_key}`
  this.SITE_52 = `https://api.rss2json.com/v1/api.json?rss_url=http%3A%2F%2Fchijofile.com%2Ffeed&api_key=${api_key}`
  this.SITE_53 = `https://api.rss2json.com/v1/api.json?rss_url=http%3A%2F%2Ferotama.net%2F%3Ffeed%3Drss2&api_key=${api_key}`
  this.SITE_54 = `https://api.rss2json.com/v1/api.json?rss_url=http%3A%2F%2Feroboss.jp%2Ffeed&api_key=${api_key}`
  this.SITE_55 = `https://api.rss2json.com/v1/api.json?rss_url=http%3A%2F%2Fnicoero-tube.com%2Ffeed%2F&api_key=${api_key}`
  this.SITE_56 = `https://api.rss2json.com/v1/api.json?rss_url=http%3A%2F%2Ffeeds.feedburner.com%2Feroantenna&api_key=${api_key}`
  this.SITE_57 = `https://api.rss2json.com/v1/api.json?rss_url=http%3A%2F%2Flove-jav.jp%2F%3Fxml&api_key=${api_key}`
  this.SITE_58 = `https://api.rss2json.com/v1/api.json?rss_url=http%3A%2F%2Fkyojiri.com%2Ffeed&api_key=${api_key}`
  this.SITE_59 = `https://api.rss2json.com/v1/api.json?rss_url=http%3A%2F%2Favjoy.net%2F%3Fxml&api_key=${api_key}`
  this.SITE_60 = `https://api.rss2json.com/v1/api.json?rss_url=http%3A%2F%2Fwww.jukujo2.com%2Ffeed&api_key=${api_key}`
  this.SITE_61 = `https://api.rss2json.com/v1/api.json?rss_url=http%3A%2F%2Fthijo-seiheki.com%2Ffeed%2F&api_key=${api_key}`
  this.SITE_62 = `https://api.rss2json.com/v1/api.json?rss_url=http%3A%2F%2Fkr3krs.com%2F%3Fxml&api_key=${api_key}`
  this.SITE_63 = `https://api.rss2json.com/v1/api.json?rss_url=http%3A%2F%2Fjp-xvideos-xvideo.com%2Ffeed&api_key=${api_key}`
  this.SITE_64 = `https://api.rss2json.com/v1/api.json?rss_url=http%3A%2F%2Ftekokeyland.com%2Ffeed&api_key=${api_key}`
  this.SITE_65 = `https://api.rss2json.com/v1/api.json?rss_url=http%3A%2F%2Fwww.hamedream.xyz%2Ffeed%2F&api_key=${api_key}`
  this.SITE_66 = `https://api.rss2json.com/v1/api.json?rss_url=http%3A%2F%2Fchijolog.com%2Ffeed&api_key=${api_key}`
  this.SITE_67 = `https://api.rss2json.com/v1/api.json?rss_url=http%3A%2F%2Fero-mink.com%2Ffeed&api_key=${api_key}`
  this.SITE_68 = `https://api.rss2json.com/v1/api.json?rss_url=http%3A%2F%2Ferobox.site%2Ffeed&api_key=${api_key}`
  this.SITE_69 = `https://api.rss2json.com/v1/api.json?rss_url=http%3A%2F%2Fpinkymine.blog.fc2.com%2F%3Fxml&api_key=${api_key}`
  this.SITE_70 = `https://api.rss2json.com/v1/api.json?rss_url=http%3A%2F%2Ftarokend.com%2Ffeed&api_key=${api_key}`
  this.SITE_71 = `https://api.rss2json.com/v1/api.json?rss_url=http%3A%2F%2Fjukuerois.com%2Frss.xml&api_key=${api_key}`
  this.SITE_72 = `https://api.rss2json.com/v1/api.json?rss_url=http%3A%2F%2Fonanuking.com%2Fpage-rss&api_key=${api_key}`
  this.SITE_73 = `https://api.rss2json.com/v1/api.json?rss_url=http%3A%2F%2Favjoy.net%2F%3Fxml&api_key=${api_key}`
  this.SITE_74 = `https://api.rss2json.com/v1/api.json?rss_url=http%3A%2F%2Fhitojyuku.tokyo%2F%3Ffeed%3Drss2&api_key=${api_key}`
  this.SITE_75 = `https://api.rss2json.com/v1/api.json?rss_url=http%3A%2F%2Frt55.me%2Ffeed%2F&api_key=${api_key}`
  this.SITE_76 = `https://api.rss2json.com/v1/api.json?rss_url=http%3A%2F%2Ffreehamechin.com%2Ffeed&api_key=${api_key}`
  this.SITE_77 = `https://api.rss2json.com/v1/api.json?rss_url=http%3A%2F%2Fpakohame.xyz%2Ffeed&api_key=${api_key}`
  this.SITE_78 = `https://api.rss2json.com/v1/api.json?rss_url=http%3A%2F%2Fmomoiro-beach.com%2Ffeed%2F&api_key=${api_key}`
  this.SITE_79 = `https://api.rss2json.com/v1/api.json?rss_url=http%3A%2F%2Fdougan-bijo-douga.info%2Ffeed&api_key=${api_key}`
  this.SITE_80 = `https://api.rss2json.com/v1/api.json?rss_url=http%3A%2F%2Fmaniahentai.com%2Ffeed&api_key=${api_key}`
  this.SITE_81 = `https://api.rss2json.com/v1/api.json?rss_url=http%3A%2F%2Fwww.deepfera.com%2Ffeed%2F&api_key=${api_key}`
  }
}
